version: '3.9'

services:
  db:
    image: postgres
    container_name: base-postgre
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks: 
      - net
      
  usuarioservice:
    build:
      context: ./src/Usuario
      dockerfile: Dockerfile
    # Configurações adicionais para o micro serviço Usuários
    container_name: usuarios-service
    networks: 
      - net
    ports:
      - 5000:5000 # Porta mapeada para acesso externo
    depends_on:
      - db
  
  boletoservice:
    build:
      context: ./src/Boleto
      dockerfile: Dockerfile
    # Configurações adicionais para o micro serviço Usuários
    container_name: boleto-service
    networks: 
      - net
    ports:
      - 5003:5003 # Porta mapeada para acesso externo
    depends_on:
      - db
  
  apifinanceiroservice:
    build:
      context: ./src/ApiFinanceiro
      dockerfile: Dockerfile
    # Configurações adicionais para o micro serviço Usuários
    container_name: apifinanceiro-service
    networks: 
      - net
    ports:
      - 5001:5001 # Porta mapeada para acesso externo

  cursoservice:
    build:
      context: ./src/Curso
      dockerfile: Dockerfile
    # Configurações adicionais para o micro serviço Usuários
    container_name: cursos-service
    networks: 
      - net
    ports:
      - 5004:5004 # Porta mapeada para acesso externo
    depends_on:
      - db
      

  identity_server_anima_service:
    build:
      context: ./src/identity_server_anima
      dockerfile: Dockerfile
    # Configurações adicionais para o micro serviço Usuários
    container_name: identity_server_anima
    networks: 
      - net
    ports:
      - 5005:5005 # Porta mapeada para acesso externo
    depends_on:
      - db
      
  matriculaservice:
    build:
      context: ./src/Matricula
      dockerfile: Dockerfile
    # Configurações adicionais para o micro serviço Usuários
    container_name: matricula-service
    networks: 
      - net
    ports:
      - 5006:5006 # Porta mapeada para acesso externo
    depends_on:
      - db
      
  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    # Configurações adicionais para o front-end Vue.js
    networks: 
      - net
    ports:
      - "8000:80"  # Porta mapeada para acesso externo

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
 
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    networks: 
      - net
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks: 
  net:
    driver: bridge
    

#  certificadosservice:
#    build:
#      context: ./src/Certificados/Certificados.API
#      dockerfile: ../../docker/certificadosservice.dockerfile
#    # Configurações adicionais para o micro serviço Certificados
#    ports:
#      - "8002:80"  # Porta mapeada para acesso externo
#
#  mensalidadesservice:
#    build:
#      context: ./src/Mensalidades/Mensalidades.API
#      dockerfile: ../../docker/mensalidadesservice.dockerfile
#    # Configurações adicionais para o micro serviço Mensalidades
#    ports:
#      - "8003:80"  # Porta mapeada para acesso externo
#
#  notasservice:
#    build:
#      context: ./src/Notas/Notas.API
#      dockerfile: ../../docker/notasservice.dockerfile
#    # Configurações adicionais para o micro serviço Notas
#    ports:
#      - "8004:80"  # Porta mapeada para acesso externo
#
#  cursosservice:
#    build:
#      context: ./src/Cursos/Cursos.API
#      dockerfile: ../../docker/cursosservice.dockerfile
#    # Configurações adicionais para o micro serviço Cursos
#    ports:
#      - "8005:80"  # Porta mapeada para acesso externo
#
#  sapintegration:
#    build:
#      context: ./src/Integracoes/SAP
#      dockerfile: ../../docker/integracoes/sap.dockerfile
#    # Configurações adicionais para a integração com SAP
#
#  servicenowintegration:
#    build:
#      context: ./src/Integracoes/ServiceNow
#      dockerfile: ../../docker/integracoes/servicenow.dockerfile
#    # Configurações adicionais para a integração com ServiceNow
#
#  webhookservice:
#    build:
#      context: ./src/WebHook/WebHook.API
#      dockerfile: ../../docker/webhookservice.dockerfile
#    # Configurações adicionais para o micro serviço WebHook
#    ports:
#      - "8006:80"  # Porta mapeada para acesso externo
#


#oracle:
#    image: wnameless/oracle-xe-11g
#    container_name: base-oracle
#    ports:
#      - 1521:1521
#    volumes:
#      - ./data:/u01/app/oracle/data