// <auto-generated />
using System;
using Boleto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Boleto.API.Migrations
{
    [DbContext(typeof(BoletoDbContext))]
    partial class BoletoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Boleto.Domain.Models.BoletoModel", b =>
                {
                    b.Property<int>("IdBoleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idboleto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBoleto"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datageracao");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datavencimento");

                    b.Property<int>("IdMatricula")
                        .HasColumnType("integer")
                        .HasColumnName("idmatricula");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mesreferencia");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean")
                        .HasColumnName("pago");

                    b.Property<string>("UrlBoleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("urlboleto");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("IdBoleto");

                    b.ToTable("boleto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
