-- Criar o banco de dados "servico_usuario"
CREATE DATABASE servico_usuario;
/*
-- Conceder permissões ao usuário "postgre" no banco de dados "servico_usuario"
GRANT ALL PRIVILEGES ON DATABASE servico_usuario TO postgre;

-- Alterar para o banco de dados "servico_usuario"
\c servico_usuario;

-- Conceder permissões ao usuário "postgre" no esquema "public"
GRANT ALL PRIVILEGES ON SCHEMA public TO postgre;

-- Finalizar
\q
*/
-- public.usuario definition

-- Drop table

-- DROP TABLE public.usuario;

CREATE TABLE public.usuario (
	idusuario int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NOT NULL,
	login varchar(50) NOT NULL,
	senha varchar(50) NOT NULL,
	email varchar(50) NOT NULL,
	celular varchar(20) NOT NULL,
	cpf varchar(20) NOT NULL,
	datanascimento timestamptz NOT NULL,
	administrador bool NOT NULL,
	CONSTRAINT "PK_usuario" PRIMARY KEY (idusuario)
);

-- Permissions

ALTER TABLE public.usuario OWNER TO postgres;
GRANT ALL ON TABLE public.usuario TO postgres;