// <auto-generated />
using Curso.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Curso.Api.Migrations
{
    [DbContext(typeof(CursoDbContext))]
    [Migration("20230725042257_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Curso.Domain.Models.CategoriaModel", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("IdCategoria");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("Curso.Domain.Models.CursoModel", b =>
                {
                    b.Property<int>("idCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_curso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCurso"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("integer")
                        .HasColumnName("carga_horaria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("idCurso");

                    b.ToTable("curso", (string)null);
                });

            modelBuilder.Entity("Curso.Domain.Models.CursoOfertaModel", b =>
                {
                    b.Property<int>("IdCursoOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_curso_oferta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCursoOferta"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdCurso")
                        .HasColumnType("integer")
                        .HasColumnName("id_curso");

                    b.Property<int>("IdModelo")
                        .HasColumnType("integer")
                        .HasColumnName("id_modelo");

                    b.Property<int>("IdTurno")
                        .HasColumnType("integer")
                        .HasColumnName("id_turno");

                    b.HasKey("IdCursoOferta");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdModelo");

                    b.HasIndex("IdTurno");

                    b.ToTable("curso_oferta", (string)null);
                });

            modelBuilder.Entity("Curso.Domain.Models.ModeloModel", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_modelo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdModelo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("IdModelo");

                    b.ToTable("modelo", (string)null);
                });

            modelBuilder.Entity("Curso.Domain.Models.TurnoModel", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_turno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTurno"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("IdTurno");

                    b.ToTable("turno", (string)null);
                });

            modelBuilder.Entity("Curso.Domain.Models.CursoOfertaModel", b =>
                {
                    b.HasOne("Curso.Domain.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Curso.Domain.Models.CursoModel", "Curso")
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Curso.Domain.Models.ModeloModel", "Modelo")
                        .WithMany()
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Curso.Domain.Models.TurnoModel", "Turno")
                        .WithMany()
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Curso");

                    b.Navigation("Modelo");

                    b.Navigation("Turno");
                });
#pragma warning restore 612, 618
        }
    }
}
